---
# tasks file for ansible-common-mac
# - name: Make sure we have a 'wheel' group
#   group:
#     name: wheel
#     state: present
#   become: true

# - name: Allow 'wheel' group to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#     validate: visudo -cf %s
#   become: true

# - name: Add sudoers users to wheel group
#   user:
#     name: "{{ item }}"
#     groups: wheel
#     append: yes
#   with_items: "{{ sudoers }}"
#   become: true
#   ignore_errors: true

# - name: Fix oh-my-zsh permissions issue
#   file:
#     path: "{{ item }}"
#     mode: '0755'
#     recurse: yes
#   with_items: "{{ ohmyzsh_folders }}"
#   become: true
- name: "Install Homebrew TAP Packages"
  community.general.homebrew_tap:
    name: "{{ packages }}"
  vars:
    packages:
      - 'homebrew/cask'
      - 'homebrew/cask-versions'
      - 'homebrew/core'
      - 'adoptopenjdk/openjdk'
      - 'hashicorp/tap'
      - 'universal-ctags/universal-ctags'
      - 'heroku/brew'
  ignore_errors: true

- name: "Install Homebrew Packages"
  community.general.homebrew:
    name: "{{ packages }}"
  vars:
    packages:
      - 'autoconf'
      - 'bash-completion'
      - 'certbot'
      - 'coreutils'
      - 'curl'
      - 'doxygen'
      - 'gcc'
      - 'gettext'
      - 'gifsicle'
      - 'git'
      - 'git-crypt'
      - 'git-flow'
      - 'git-ftp'
      - 'git-lfs'
      - 'github/gh/gh'
      - 'go'
      - 'gomplate'
      - 'gpg'
      - 'htop'
      - 'httpie'
      - 'hub'
      - 'hudochenkov/sshpass/sshpass'
      - 'imagemagick'
      - 'iperf'
      - 'jq'
      - 'libevent'
      - 'libyaml'
      - 'openssl'
      - 'pv'
      - 'pyenv'
      - 'python'
      - 'rbenv'
      - 'rcm'
      - 'readline'
      - 'reattach-to-user-namespace'
      - 'ruby-build'
      - 'sambadevi/powerlevel9k/powerlevel9k'
      - 'sqlite'
      - 'ssh-copy-id'
      - 'the_silver_searcher'
      - 'tmux'
      - 'tree'
      - 'vim'
      - 'watch'
      - 'watchman'
      - 'wget'
      - 'wrk'
      - 'xz'
      - 'yarn'
      - 'zsh-syntax-highlighting'
    state: present
    update_homebrew: yes
    upgrade_all: yes
  register: brew_common_result
  ignore_errors: true
  failed_when: "'Error:' in brew_common_result.stderr"